# Generated by Django 6.0.4 on 2026-04-27 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('destinatario', models.CharField(choices=[('TODOS', 'Todos'), ('DOCENTES', 'Docentes'), ('CURSO', 'Curso específico')], default='TODOS', max_length=20)),
                ('archivado', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(blank=True, help_text='Solo si el destinatario es un curso específico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.curso')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LecturaComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='comunicados.comunicado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comunicado', 'usuario')},
            },
        ),
    ]
