# Generated by Django 6.0.6 on 2026-07-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=5)),
                ('division', models.CharField(max_length=2)),
                ('materia', models.CharField(max_length=50)),
                ('nota1', models.IntegerField()),
                ('nota2', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Calificación de alumno',
                'verbose_name_plural': 'Calificaciones de alumnos',
            },
        ),
    ]
