# Generated by Django 6.0.6 on 2026-07-02 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=5)),
                ('division', models.CharField(max_length=2)),
                ('materia', models.CharField(max_length=50)),
                ('nota1', models.IntegerField()),
                ('nota2', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Calificación de alumno',
                'verbose_name_plural': 'Calificaciones de alumnos',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('1C', '1° Cuatrimestre'), ('2C', '2° Cuatrimestre'), ('3C', '3° Cuatrimestre'), ('4C', '4° Cuatrimestre')], max_length=2)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='alumnos.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='docentes.materia')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['alumno', 'materia', 'periodo'],
                'unique_together': {('alumno', 'materia', 'periodo')},
            },
        ),
    ]
