# Migración 0001_initial.py
# Una migración es un archivo que Django genera automáticamente cuando detecta cambios en models.py
# Cada migración contiene instrucciones SQL para crear, modificar o eliminar tablas en la BD
# Django ejecuta las migraciones en orden numérico para mantener la BD sincronizada con los modelos

# Generated by Django 6.0.4 on 2026-04-27 01:05  # Línea generada automáticamente: versión de Django + fecha/hora de creación

import django.db.models.deletion  # Importa el módulo para definir claves foráneas (ForeignKeys) en migraciones
from django.db import migrations, models  # migrations: herramientas para crear/modificar tablas; models: tipos de campo (CharField, IntegerField, etc.)


class Migration(migrations.Migration):  # Cada migración es una clase que hereda de migrations.Migration

    initial = True  # initial = True marca esta migración como la primera de la app. Django la usa para saber que la tabla ya existe

    dependencies = [  # dependencies: lista de migraciones que DEBEN ejecutarse antes que esta (porque esta migración las necesita)
        ('alumnos', '0001_initial'),  # Esta migración depende de la migración 0001_initial de la app 'alumnos'
        ('docentes', '0001_initial'),  # Y también de la 0001_initial de la app 'docentes'
    ]

    operations = [  # operations: lista de cosas que hacer en la BD (crear tabla, agregar columna, etc.)
        migrations.CreateModel(  # CreateModel: le dice a Django que ejecute CREATE TABLE en SQL
            name='Calificacion',  # name: nombre del modelo (Django lo convierte a snake_case para la tabla: "calificaciones_calificacion")
            fields=[  # fields: lista de columnas que va a tener la tabla
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # BigAutoField: entero auto-incremental de 64 bits. auto_created=True: Django lo agrega solo si no definís una PK. primary_key=True: es la clave primaria. serialize=False: no se incluye al serializar
                ('periodo', models.CharField(choices=[('1B', '1° Bimestre'), ('2B', '2° Bimestre'), ('3B', '3° Bimestre'), ('4B', '4° Bimestre')], max_length=2)),  # CharField con choices: el campo solo acepta esos valores; en SQL es VARCHAR(2) con CHECK constraint
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),  # DecimalField: DECIMAL(4,2) en SQL
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='alumnos.alumno')),  # ForeignKey: crea columna alumno_id, referencia a tabla alumnos_alumno. related_name: permite navegación inversa. on_delete=CASCADE: ON DELETE CASCADE
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='docentes.materia')),  # FK a docentes_materia. related_name: materia.calificaciones.all()
            ],
            options={  # Opciones de la tabla (misma información que class Meta en models.py)
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['alumno', 'materia', 'periodo'],  # ORDER BY por defecto
                'unique_together': {('alumno', 'materia', 'periodo')},  # UNIQUE(alumno, materia, periodo)
            },
        ),
    ]
