# Generated by Django 6.0.4 on 2026-06-22 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(verbose_name='Año lectivo')),
                ('curso', models.CharField(max_length=5, verbose_name='Curso')),
                ('division', models.CharField(max_length=5, verbose_name='División')),
                ('materia', models.CharField(max_length=100, verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-año', 'curso', 'division', 'materia'],
                'unique_together': {('año', 'curso', 'division', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='calificaciones.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de evaluación')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Valor (0-10)')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='calificaciones.alumno', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['tipo'],
                'unique_together': {('alumno', 'tipo')},
            },
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
