# Generated by Django 6.0.6 on 2026-09-17 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('calificaciones', '0001_initial'),
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuatrimestre', models.IntegerField(choices=[(1, '1° Cuatrimestre'), (2, '2° Cuatrimestre')], unique=True)),
                ('publicado', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de boletín',
                'verbose_name_plural': 'Configuraciones de boletines',
            },
        ),
        migrations.CreateModel(
            name='CategoriaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Trabajo Práctico, Examen, Participación', max_length=100)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la grilla')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='docentes.materia')),
            ],
            options={
                'verbose_name': 'Categoría de evaluación',
                'verbose_name_plural': 'Categorías de evaluación',
                'ordering': ['materia', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='NotaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuatrimestre', models.IntegerField(choices=[(1, '1° Cuatrimestre'), (2, '2° Cuatrimestre')])),
                ('valor', models.DecimalField(decimal_places=1, max_digits=4)),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Primer parcial, TP N°3', max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_evaluacion', to='alumnos.alumno')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='calificaciones.categoriaevaluacion')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_evaluacion', to='docentes.materia')),
            ],
            options={
                'verbose_name': 'Nota de evaluación',
                'verbose_name_plural': 'Notas de evaluación',
            },
        ),
    ]
