# Generated by Django 6.1.1 on 2026-09-03 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_alumnocalificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuatrimestre', models.IntegerField(choices=[(1, '1° Cuatrimestre'), (2, '2° Cuatrimestre')], unique=True)),
                ('publicado', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de boletín',
                'verbose_name_plural': 'Configuraciones de boletines',
            },
        ),
        migrations.CreateModel(
            name='CategoriaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Trabajo Práctico, Examen, Participación', max_length=100)),
                ('materia_nombre', models.CharField(help_text='Nombre exacto de la materia', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la grilla')),
            ],
            options={
                'verbose_name': 'Categoría de evaluación',
                'verbose_name_plural': 'Categorías de evaluación',
                'ordering': ['materia_nombre', 'orden', 'nombre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='alumnocalificacion',
            unique_together={('nombre', 'materia')},
        ),
        migrations.CreateModel(
            name='NotaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuatrimestre', models.IntegerField(choices=[(1, '1° Cuatrimestre'), (2, '2° Cuatrimestre')])),
                ('valor', models.DecimalField(decimal_places=1, max_digits=4)),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Primer parcial, TP N°3', max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('alumno_calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='calificaciones.alumnocalificacion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='calificaciones.categoriaevaluacion')),
            ],
            options={
                'verbose_name': 'Nota de evaluación',
                'verbose_name_plural': 'Notas de evaluación',
            },
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
        migrations.RemoveField(
            model_name='alumnocalificacion',
            name='nota1',
        ),
        migrations.RemoveField(
            model_name='alumnocalificacion',
            name='nota2',
        ),
    ]
