# Generated by Django 6.0.4 on 2026-06-22 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_curso_alumno_evaluacion_delete_calificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI (usuario para login)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Django'),
        ),
    ]
