# Generated by Django 6.1.1 on 2026-09-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_boletinconfig_categoriaevaluacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnocalificacion',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Calificación de alumno', 'verbose_name_plural': 'Calificaciones de alumnos'},
        ),
        migrations.AlterUniqueTogether(
            name='alumnocalificacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alumnocalificacion',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alumnocalificacion',
            name='dni',
            field=models.CharField(blank=True, default='', help_text='Clave para unir con el padrón real', max_length=20, verbose_name='DNI'),
        ),
        migrations.AlterUniqueTogether(
            name='alumnocalificacion',
            unique_together={('nombre', 'apellido', 'materia')},
        ),
    ]
