# Generated by Django 6.0.4 on 2026-06-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_alumno_dni_alumno_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='user',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI del alumno'),
        ),
    ]
