# Generated by Django 6.1.1 on 2026-09-03 17:25

from django.db import migrations


def descomponer_nombres(apps, schema_editor):
    AlumnoCalificacion = apps.get_model("calificaciones", "AlumnoCalificacion")

    # DNI de ejemplo solo para los alumnos ya cargados, para que el
    # ABM y la futura integración con el padrón real tengan clave.
    # Se sobrescriben cuando el resto de los grupos cargue el padrón.
    # Usamos un hash corto estable basado en (`apellido`, `nombre`) y materia.
    dnies = {}

    def dni_para(apellido, nombre, materia):
        base = f"{apellido.strip()}|{nombre.strip()}".lower()
        if base not in dnies:
            # DNI sintético determinístico 8 dígitos, sin colisiones por nombre
            suma = sum((ord(c) for c in base)) + len(base) * 1000
            dnies[base] = str(10000000 + (suma % 9999999))
        return dnies[base]

    for alumno in AlumnoCalificacion.objects.all():
        # Nombre viene como "Apellido, Nombre"
        nombre_completo = alumno.nombre.strip()
        if "," in nombre_completo:
            apellido, nombre = [p.strip() for p in nombre_completo.split(",", 1)]
        else:
            partes = nombre_completo.split(" ", 1)
            apellido = partes[0] if len(partes) > 1 else ""
            nombre = partes[-1] if len(partes) > 1 else nombre_completo

        alumno.apellido = apellido
        alumno.nombre = nombre
        alumno.dni = dni_para(apellido, nombre, alumno.materia)
        alumno.save()


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_alter_alumnocalificacion_options_and_more'),
    ]

    operations = [
        migrations.RunPython(descomponer_nombres),
    ]
