# Generated by Django 6.0.4 on 2026-06-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0005_alter_alumno_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado manual (opcional)'),
        ),
    ]
