# Migración 0007_mensaje.py: crea la tabla "calificaciones_mensaje" para el modelo Mensaje
# Django genera esto automáticamente con "python manage.py makemigrations" después de agregar la clase Mensaje en models.py

# Generated by Django 6.0.4 on 2026-06-22 06:36  # Fecha exacta de cuándo se generó esta migración

import django.db.models.deletion  # Importa la función que define el comportamiento de claves foráneas (on_delete)
from django.db import migrations, models  # migrations para CreateModel/AddField; models para tipos de campo


class Migration(migrations.Migration):  # Clase que representa una migración.

    dependencies = [  # migrations que deben ejecutarse ANTES que esta (porque esta necesita que exista la tabla Curso)
        ('calificaciones', '0006_alumno_estado'),  # Depende de la migración 0006 de la misma app calificaciones (que agregó el campo estado a Alumno)
    ]

    operations = [  # Lista de operaciones a ejecutar en la BD
        migrations.CreateModel(  # CREATE TABLE calificaciones_mensaje
            name='Mensaje',  # Nombre del modelo en Django (la tabla SQL se llama calificaciones_mensaje automáticamente)
            fields=[  # Columnas de la tabla
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # id: entero auto-incremental de 64 bits. auto_created: Django lo genera solo. primary_key: es la PK. serialize: no se serializa
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),  # Columna VARCHAR(200) con etiqueta "Título"
                ('contenido', models.TextField(verbose_name='Contenido')),  # Columna TEXT (sin límite de caracteres) con etiqueta "Contenido"
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),  # Columna DATETIME. auto_now_add=True: se setea la fecha actual automáticamente al INSERTAR (no al actualizar)
                ('curso', models.ForeignKey(  # ForeignKey: crea columna curso_id que referencia a la tabla calificaciones_curso
                    on_delete=django.db.models.deletion.CASCADE,  # ON DELETE CASCADE: si se borra el curso, se borra el mensaje
                    related_name='mensajes',  # related_name: curso.mensajes.all() para obtener mensajes de un curso
                    to='calificaciones.curso',  # to: a qué app.modelo apunta la FK
                    verbose_name='Curso'
                )),
            ],
            options={  # Metadatos de la tabla (traducidos de class Meta en models.py)
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-creado'],  # ORDER BY creado DESC: los más nuevos primero
            },
        ),
    ]
