# Generated by Django 6.0.4 on 2026-06-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0007_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del profesor'),
        ),
    ]
