# Migración 0009_notadireccion.py: crea la tabla "calificaciones_notadireccion" para el modelo NotaDireccion
# Esta migración se generó cuando agregué la clase NotaDireccion en models.py y ejecuté "python manage.py makemigrations"

# Generated by Django 6.0.4 on 2026-06-22 06:52  # Fecha de generación automática

import django.db.models.deletion  # Para el parámetro on_delete de las ForeignKey
from django.db import migrations, models  # migrations y tipos de campo


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0008_curso_profesor'),  # Depende de la migración 0008, que agregó el campo "profesor" al modelo Curso
    ]

    operations = [
        migrations.CreateModel(  # CREATE TABLE calificaciones_notadireccion
            name='NotaDireccion',  # Nombre del modelo
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # PK auto-incremental de 64 bits
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),  # VARCHAR(200): título del reporte
                ('mensaje', models.TextField(verbose_name='Mensaje')),  # TEXT: cuerpo del reporte
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),  # DATETIME: se autogenera al insertar
                ('alumno', models.ForeignKey(  # FK a calificaciones_alumno: crea columna alumno_id
                    on_delete=django.db.models.deletion.CASCADE,  # CASCADE: si el alumno se borra, su reporte también
                    related_name='notas_direccion',
                    to='calificaciones.alumno',
                    verbose_name='Alumno'
                )),
                ('curso', models.ForeignKey(  # FK a calificaciones_curso: crea columna curso_id
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='notas_direccion',
                    to='calificaciones.curso',
                    verbose_name='Curso'
                )),
            ],
            options={
                'verbose_name': 'Nota a Dirección',
                'verbose_name_plural': 'Notas a Dirección',
                'ordering': ['-creado'],  # ORDER BY creado DESC
            },
        ),
    ]
